server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trueshot?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: AdobeAi@0112
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mail:
    host: localhost
    port: 2525
    username: dummy
    password: dummy
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
logging:
  level:
    com:
      ongtangco:
        trueshot: TRACE
app:
  info:
    storeName: "Trueshot Camera Exchange"
    supportEmail: "support@trueshot.local"
    supportNumber: "+63-900-123-4567"
    heroMessage: "Find your next camera companion."
